name: semantic_uncertainty_export
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.8.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow=1.2.3=py311h06a4308_1
  - arrow-cpp=11.0.0=h374c478_2
  - async-timeout=4.0.2=py311h06a4308_0
  - attrs=23.1.0=py311h06a4308_0
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.5=py311hbed6279_0
  - brotlipy=0.7.0=py311h5eee18b_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - certifi=2023.11.17=py311h06a4308_0
  - cffi=1.15.1=py311h5eee18b_3
  - chardet=4.0.0=py311h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311h06a4308_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=41.0.3=py311hdda0065_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - datasets=2.12.0=py311h06a4308_0
  - dill=0.3.6=py311h06a4308_0
  - evaluate=0.4.0=py311h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.3.3=py311h5eee18b_0
  - fsspec=2023.9.2=py311h06a4308_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - huggingface_hub=0.17.3=py311h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.4=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jinja2=3.1.2=py311h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.0.34=0
  - libcurand=10.3.4.52=0
  - libcurl=8.4.0=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.2=py311h5eee18b_0
  - multiprocess=0.70.14=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py311h06a4308_0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.0=py311h08b1b3b_0
  - numpy-base=1.26.0=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - packaging=23.1=py311h06a4308_0
  - pillow=10.0.1=py311ha6cbd5a_0
  - pip=23.3.1=py311h06a4308_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - pyarrow=11.0.0=py311hd8e8d9b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.2.0=py311h06a4308_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - pytorch=2.1.1=py3.11_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py311h06a4308_0
  - pyyaml=6.0=py311h5eee18b_1
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py311h06a4308_0
  - responses=0.13.3=pyhd3eb1b0_0
  - setuptools=68.0.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=h295c915_0
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.11.1=py311h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=2.1.1=py311_cu118
  - torchtriton=2.1.0=py311
  - torchvision=0.16.1=py311_cu118
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.16=py311h06a4308_0
  - utf8proc=2.6.1=h27cfd23_0
  - wheel=0.41.2=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py311h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - absl-py==2.0.0
    - accelerate==0.25.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.9.3
    - anyio==3.7.1
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.4.0
    - async-lru==2.0.4
    - babel==2.13.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bitsandbytes==0.41.2.post2
    - bleach==6.1.0
    - comm==0.1.4
    - contextlib2==21.6.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - debugpy==1.8.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distro==1.8.0
    - docker-pycreds==0.4.0
    - einops==0.7.0
    - executing==2.0.0
    - fastjsonschema==2.18.1
    - flake8==6.1.0
    - fonttools==4.43.1
    - fqdn==1.5.1
    - gitdb==4.0.11
    - gitpython==3.1.40
    - h11==0.14.0
    - httpcore==1.0.1
    - httpx==0.25.1
    - ipykernel==6.25.2
    - ipython==8.16.1
    - ipywidgets==8.1.1
    - isoduration==20.11.0
    - jedi==0.19.1
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.4.0
    - jupyter-core==5.4.0
    - jupyter-events==0.8.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.8.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.9
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - jupyterlab-widgets==3.0.9
    - kiwisolver==1.4.5
    - lightning-utilities==0.9.0
    - matplotlib==3.8.2
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==3.0.2
    - ml-collections==0.1.1
    - nbclient==0.8.0
    - nbconvert==7.9.2
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - nltk==3.8.1
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - omegaconf==2.3.0
    - openai==1.3.7
    - overrides==7.4.0
    - pandas==2.1.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - platformdirs==3.11.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==4.24.4
    - psutil==5.9.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycodestyle==2.11.1
    - pydantic==2.4.2
    - pydantic-core==2.10.1
    - pyflakes==3.1.0
    - pygments==2.16.1
    - pyparsing==3.1.1
    - python-json-logger==2.0.7
    - pyzmq==25.1.1
    - referencing==0.30.2
    - regex==2023.10.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - safetensors==0.4.1
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - seaborn==0.13.0
    - send2trash==1.8.2
    - sentencepiece==0.1.99
    - sentry-sdk==1.32.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - sniffio==1.3.0
    - soupsieve==2.5
    - stack-data==0.6.3
    - tenacity==8.2.3
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tiktoken==0.5.2
    - tinycss2==1.2.1
    - tokenizers==0.15.0
    - torchmetrics==1.2.1
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.11.2
    - transformers==4.35.2
    - uri-template==1.3.0
    - wandb==0.16.0
    - wcwidth==0.2.8
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - widgetsnbextension==4.0.9
